### ISSUE TITLE
Difficulty Adjustment Bug (0.15 branch)

### ISSUE THREAD

**Issue by HashEngineering** [bitcoinj-cash/bitcoinj#23]
When using checkpoints, the November 13 DAA will fail.  This was resolved with #18 on `cash-0.14` with https://github.com/bitcoinj-cash/bitcoinj/pull/18/files#diff-ef262b65e6add81fc5f71fd7a4e2d82cR242

on `getPrev()`, check for null and if it is null throw `BlockStoreException`.

By way of reminder, checkpoints allow the app to start syncing the blockchain at arbitrary block heights instead of starting from block 0.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.bitcoinj.core.StoredBlock org.bitcoinj.core.StoredBlock.getPrev(org.bitcoinj.store.BlockStore)' on a null object reference
at org.bitcoinj.pow.rule.NewDifficultyAdjustmentAlgorithmRulesChecker.GetMostSuitableBlock(NewDifficultyAdjustmentAlgorithmRulesChecker.java:72) ~[na:0.0]
at org.bitcoinj.pow.rule.NewDifficultyAdjustmentAlgorithmRulesChecker.checkNextCashWorkRequired(NewDifficultyAdjustmentAlgorithmRulesChecker.java:49) ~[na:0.0]
at org.bitcoinj.pow.rule.NewDifficultyAdjustmentAlgorithmRulesChecker.checkRules(NewDifficultyAdjustmentAlgorithmRulesChecker.java:32) ~[na:0.0]
at org.bitcoinj.pow.RulesPoolChecker.checkRules(RulesPoolChecker.java:22) ~[na:0.0]
at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:494) ~[na:0.0]
at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:357) ~[na:0.0]
at org.bitcoinj.core.Peer.processHeaders(Peer.java:703) ~[na:0.0]
at org.bitcoinj.core.Peer.processMessage(Peer.java:504) ~[na:0.0]
at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:142) ~[na:0.0]
at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[na:0.0]
at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[na:0.0]
at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) ~[na:0.0]
at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by HashEngineering** [comment]
Similar bug with the EDA:
```
05:16:06 [NioClientManager] Peer - Block header verification failed
org.bitcoinj.core.VerificationException: Could not verify block:
 block: 
   hash: 000000000000000001d39a2ee084a4e48f8afa2c8159c5030a0afb59c8331453
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 000000000000000002908d41030b2e95b2306d8a1e331fca1a5b0066287813e1
   merkle root: d75ee3e9f4b0192e0cdc4952af645cd73be28aee061f4f3d950040a0f206b2a2
   time: 1503884805 (2017-08-28T01:46:45Z)
   difficulty target (nBits): 402962250
   nonce: 3353196710

	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:368) ~[na:0.0]
	at org.bitcoinj.core.Peer.processHeaders(Peer.java:703) ~[na:0.0]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:504) ~[na:0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:142) ~[na:0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: org.bitcoinj.core.VerificationException: Unexpected change in difficulty at height 483852: 1804b74a vs 1803c5d5
	at org.bitcoinj.pow.rule.EmergencyDifficultyAdjustmentRuleChecker.throwUnexpectedDifficultyChangedException(EmergencyDifficultyAdjustmentRuleChecker.java:84) ~[na:0.0]
	at org.bitcoinj.pow.rule.EmergencyDifficultyAdjustmentRuleChecker.checkEDARules(EmergencyDifficultyAdjustmentRuleChecker.java:55) ~[na:0.0]
	at org.bitcoinj.pow.rule.EmergencyDifficultyAdjustmentRuleChecker.checkRules(EmergencyDifficultyAdjustmentRuleChecker.java:26) ~[na:0.0]
	at org.bitcoinj.pow.RulesPoolChecker.checkRules(RulesPoolChecker.java:22) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:494) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:357) ~[na:0.0]
```

**Comment by HashEngineering** [comment]
Due to the nature of checkpoints, bitcoinj will not have enough information to determine the difficulty if starting the blockchain in the EDA or after November 13.

The EDA difficulty check will fail if the syncing starts in the middle of an emergency difficulty adjustment.

I have found the fixes for both.  On the cash-0.14 branch, the EDA may not work.

Blockchain.getMedianTimestampOfRecentBlocks does not throw an exception if there are less than 10 blocks before the block in question, so it calculates a differnet median time than if there are more than 10 blocks.

**Comment by rafa-js** [comment]
How about include some specific tests to cover this cases? It already exists?

**Comment by HashEngineering** [comment]
Tests are great, but we don't have them yet.  The problem is usually not syncing from the genesis block, but instead from checkpoint after a DAA fork.

The test would be to start a particular block and stop at another while syncing with the bitcoin cash network.  What platform would allow for this?

**Comment by HashEngineering** [comment]
#67
